type Difficulty =
    | 0
    | 1
    | 2
    | 3
    | 'peaceful'
    | 'easy'
    | 'normal'
    | 'hard';

type Gamemode =
    | 0
    | 1
    | 2
    | 3
    | 'survival'
    | 'creative'
    | 'adventure'
    | 'spectator';

export interface Properties {
    readonly 'allow-flight':
        | boolean
        | null
        | undefined;
    readonly 'allow-nether':
        | boolean
        | null
        | undefined;
    readonly 'broadcast-console-to-ops':
        | boolean
        | null
        | undefined;
    readonly 'broadcast-rcon-to-ops':
        | boolean
        | null
        | undefined;
    readonly difficulty:
        | Difficulty
        | null
        | undefined;
    readonly 'enable-command-block':
        | boolean
        | null
        | undefined;
    readonly 'enable-jmx-monitoring':
        | boolean
        | null
        | undefined;
    readonly 'enable-rcon':
        | boolean
        | null
        | undefined;
    readonly 'sync-chunk-writes':
        | boolean
        | null
        | undefined;
    readonly 'enable-status':
        | boolean
        | null
        | undefined;
    readonly 'enable-query':
        | boolean
        | null
        | undefined;
    readonly 'entity-broadcast-range-percentage':
        | number
        | null
        | undefined;
    readonly 'force-gamemode':
        | boolean
        | null
        | undefined;
    readonly 'function-permission-level':
        | 1
        | 2
        | 3
        | 4
        | null
        | undefined;
    readonly gamemode:
        | Gamemode
        | null
        | undefined;
    readonly 'generate-structures':
        | boolean
        | null
        | undefined;
    readonly 'generator-settings':
        | object
        | null
        | undefined;
    readonly hardcore:
        | boolean
        | null
        | undefined;
    readonly 'level-name':
        | string
        | null
        | undefined;
    readonly 'level-seed':
        | string
        | null
        | undefined;
    readonly 'level-type':
        | string
        | null
        | undefined;
    readonly 'max-chained-neighbor-updates':
        | number
        | null
        | undefined;
    readonly 'max-players':
        | number
        | null
        | undefined;
    readonly 'max-tick-time':
        | number
        | null
        | undefined;
    readonly 'max-world-size':
        | number
        | null
        | undefined;
    readonly motd:
        | string
        | null
        | undefined;
    readonly 'network-compression-threshold':
        | number
        | null
        | undefined;
    readonly 'online-mode':
        | boolean
        | null
        | undefined;
    readonly 'op-permission-level':
        | 0
        | 1
        | 2
        | 3
        | 4
        | null
        | undefined;
    readonly 'player-idle-timeout':
        | number
        | null
        | undefined;
    readonly 'prevent-proxy-connections':
        | boolean
        | null
        | undefined;
    readonly pvp:
        | boolean
        | null
        | undefined;
    readonly 'query.port':
        | number
        | null
        | undefined;
    readonly 'rate-limit':
        | number
        | null
        | undefined;
    readonly 'rcon.password':
        | string
        | null
        | undefined;
    readonly 'rcon.port':
        | number
        | null
        | undefined;
    readonly 'resource-pack':
        | string
        | null
        | undefined;
    readonly 'resource-pack-prompt':
        | string
        | null
        | undefined;
    readonly 'resource-pack-sha1':
        | string
        | null
        | undefined;
    readonly 'require-resource-pack':
        | boolean
        | null
        | undefined;
    readonly 'server-ip':
        | string
        | null
        | undefined;
    readonly 'server-port':
        | number
        | null
        | undefined;
    readonly 'simulation-distance':
        | number
        | null
        | undefined;
    readonly 'snooper-enabled':
        | boolean
        | null
        | undefined;
    readonly 'spawn-animals':
        | boolean
        | null
        | undefined;
    readonly 'spawn-monsters':
        | boolean
        | null
        | undefined;
    readonly 'spawn-npcs':
        | boolean
        | null
        | undefined;
    readonly 'spawn-protection':
        | number
        | null
        | undefined;
    readonly 'text-filtering-config':
        | unknown
        | null
        | undefined;
    readonly 'use-native-transport':
        | boolean
        | null
        | undefined;
    readonly 'view-distance':
        | number
        | null
        | undefined;
    readonly 'white-list':
        | boolean
        | null
        | undefined;
    readonly 'enforce-whitelist':
        | boolean
        | null
        | undefined;
}
